# Generated by Django 4.2 on 2026-05-19 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REGISTRATION', 'Item registered'), ('VERIFICATION', 'Item verified'), ('REVOCATION', 'Item revoked'), ('ISSUER_APPROVED', 'Issuer approved'), ('ISSUER_REJECTED', 'Issuer rejected'), ('FRAUD_FLAGGED', 'Fraud alert raised')], max_length=20)),
                ('description', models.TextField()),
                ('actor_id', models.CharField(blank=True, help_text='ID of the user who triggered this event', max_length=255)),
                ('item_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_hash', models.CharField(help_text='Hash of the suspicious item', max_length=64)),
                ('item_id', models.CharField(blank=True, help_text='ID of the item from Item Registration Service', max_length=255)),
                ('issuer_id', models.CharField(blank=True, help_text='ID of the issuer who registered the item', max_length=255)),
                ('verification_count', models.IntegerField(default=0, help_text='Number of verifications that triggered this alert')),
                ('status', models.CharField(choices=[('OPEN', 'Open — under review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed — false positive')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
