upstream user_auth       { server 127.0.0.1:8001; }
upstream institution     { server 127.0.0.1:8002; }
upstream item_reg        { server 127.0.0.1:8003; }
upstream blockchain      { server 127.0.0.1:8004; }
upstream auth_output     { server 127.0.0.1:8005; }
upstream verification    { server 127.0.0.1:8006; }
upstream admin_analytics { server 127.0.0.1:8007; }

server {
    listen 80;
    server_name 207.180.217.238;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 207.180.217.238;

    ssl_certificate     /etc/ssl/certs/qentis.crt;
    ssl_certificate_key /etc/ssl/private/qentis.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 20M;

    location / {
        root /var/www/qentis;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://user_auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/institution/ {
        proxy_pass http://institution;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/items/ {
        proxy_pass http://item_reg;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/blockchain/ {
        proxy_pass http://blockchain;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/output/ {
        proxy_pass http://auth_output;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/verify/ {
        proxy_pass http://verification;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/admin/ {
        proxy_pass http://admin_analytics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /media/ {
        proxy_pass http://auth_output;
        proxy_set_header Host $host;
    }
}