# Generated by Django 4.2 on 2026-05-18 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(help_text='ID of the institution from Institution Management Service')),
                ('issuer_id', models.UUIDField(help_text='ID of the issuer user from User & Auth Service')),
                ('category', models.CharField(choices=[('CERTIFICATE', 'Academic Certificate'), ('PHARMACEUTICAL', 'Pharmaceutical Product'), ('DOCUMENT', 'Official Document'), ('BANKNOTE', 'Currency / Banknote')], max_length=20)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('REVOKED', 'Revoked')], default='REGISTERED', max_length=10)),
                ('blockchain_hash', models.CharField(blank=True, help_text='SHA-256 hash stored on blockchain', max_length=64, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Ethereum transaction hash', max_length=255, null=True)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('factory_location', models.CharField(max_length=255)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmaceutical_detail', to='item_app.item')),
            ],
            options={
                'db_table': 'pharmaceutical_details',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_detail', to='item_app.item')),
            ],
            options={
                'db_table': 'document_details',
            },
        ),
        migrations.CreateModel(
            name='CertificateDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('grade', models.CharField(max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_detail', to='item_app.item')),
            ],
            options={
                'db_table': 'certificate_details',
            },
        ),
        migrations.CreateModel(
            name='BanknoteDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=15)),
                ('serial_number', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('issuing_bank', models.CharField(max_length=255)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banknote_detail', to='item_app.item')),
            ],
            options={
                'db_table': 'banknote_details',
            },
        ),
    ]
