# Generated by Django 4.2 on 2026-05-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_item_approved_at_item_approved_by_item_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='fingerprint_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
