# Generated by Django 4.2 on 2026-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_documentdetail_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='credential_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
