# Generated by Django 4.2 on 2026-05-19 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(help_text='ID of the item from Item Registration Service', max_length=255)),
                ('item_hash', models.CharField(help_text='SHA-256 hash of the item', max_length=64)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Certificate'), ('PHARMA', 'Pharmaceutical Product'), ('DOCUMENT', 'Official Document'), ('CURRENCY', 'Currency / Banknote')], max_length=20)),
                ('issuer_id', models.CharField(help_text='ID of the issuer from Auth Service', max_length=255)),
                ('output_type', models.CharField(choices=[('QR_CODE', 'QR Code'), ('SERIAL', 'Serial Number'), ('SIGNATURE', 'Digital Signature'), ('WATERMARK', 'Watermark')], max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Generated serial number e.g. QNT-2026-ACAD-00123', max_length=50, null=True, unique=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated file (QR image, signed PDF, watermarked image)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'generated_outputs',
                'ordering': ['-created_at'],
            },
        ),
    ]
